### ISSUE TITLE
what's with the naming lmao 

### ISSUE THREAD

**Issue by angeldzzz23** [coderkai03/Macrohard#1]

**Comment by coderkai03** [comment]
its the opposite of Microsoft lol

**Comment by angeldzzz23** [comment]
the name of this project is the title of my sex tape

**Comment by coderkai03** [comment]
language, young man

**Comment by angeldzzz23** [comment]
Did you just freaking censor me? Who are you Elon?

**Comment by coderkai03** [comment]
im batman

**Comment by coderkai03** [comment]
also this is a class project so i have to delete this entire discussion later lol

**Comment by angeldzzz23** [comment]
@coderkai03 dont delete. Your professor will not care

**Comment by angeldzzz23** [comment]
@coderkai03 what class is this for?
